import { NextAuthProvider } from "./provider"
import Header from "@/components/header"


export const metadata = {
  title: "QuikNote",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Header />
          
          {children}
          </NextAuthProvider>
      </body>
    </html>
  )
}
